namespace: kubesphere-logging-system

namePrefix: logsidecar-injector-

resources:
- configmap.yaml
- deploy.yaml
- admission.yaml

configurations:
- kustomizeconfig.yaml

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: ADMISSION_SERVICE_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: admission
- fieldref:
    fieldPath: metadata.name
  name: ADMISSION_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: admission
- fieldref:
    fieldPath: metadata.name
  name: INJECTOR_DEPLOY_NAME
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy

images:
- name: configmap-reload
  newName: jimmidyson/configmap-reload
  newTag: v0.3.0
- name: injector
  newName: kubespheredev/log-sidecar-injector
  newTag: "1.1"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
